baseURL = "https://pug.phpday.it/"
languageCode = "it-it"
title = "phpday PUG Edition"
theme = "timer-hugo"

# We Used Ionicons Icon font for Icon, for more details check this link - https://ionicons.com/

# Navbar Menus
[[menu.main]]
name    = "PUG"
url     = "#pug"
weight  = 2
[[menu.main]]
name    = "Programma"
url     = "#programma"
weight  = 3

# Site Params
[params]
home = "Home"
logo = "images/grusp/grusp.svg"
dateFormat = "6 January 2006"
# Meta data
description = "phpday PUG Edition by GrUSP"
author = "GrUSP - Teo Miscia"
# Google Analitycs
googleAnalitycsID = "Your ID"
# contact form action
contactFormAction = "#" # contact form works with https://formspree.io

# Banner
[params.banner]
enable = true

# Homepage About Section
[params.about]
enable  = true
title   = "Di cosa si tratta?"
content = "Un fantastico evento online di due pomeriggi organizzato da GrUSP e tutti i PUG a livello nazionale. Vista l'impossibilità di organizzare il phpday a Verona a causa del COVID-19 abbiamo pensato di organizzare un'edizione online gratuita dell'evento negli stessi giorni in cui era prevista la conferenza.<br/> L’evento sarà in italiano. Ogni sessione durerà 45 min: 30 min di talk e 15 min di Q&A. Sarà possibile interagire tra i partecipanti anche attraverso lo slack del GrUSP sul canale #phpday."
days_number = "2"
days_desc = "Pomeriggi"
talks_number = "8"
talks_desc = "Talk"

# Homepage About2 Section
[params.about2]
enable  = true
title   = "Chi sono i PUG?"
content = 'I PUG sono i PHP User Group: community locali dislocate su tutto il territorio nazionale che organizzano meetup verticali php e non solo.<br/>Negli anni GrUSP ha favorito la nascita dei PUG supportando i vari gruppi da un punto di vista organizzativo, promozionale ed economico.<br/>Partecipa ai meetup del <a href="http://www.grusp.org/it/pug.html" target="_blank">PUG più vicino a te!</a>'
image = "images/grusp/PUG_Club.svg"

# Call to Action
[params.cta]
enable  = true
btnText = "ISCRIVITI GRATUITAMENTE"
btnURL  = "https://phpday-pug-ed.eventbrite.it/"

# I PUG

[[params.pug]]
icon = "images/grusp/pug-catania.jpg"
title = "PUG Catania"
abstract = "Il PUG Catania rinasce dopo qualche anno di inattività a novembre 2019 organizzando il primo meetup già a dicembre 2019.<br/>Lo scopo è quello di ricostruire la community di sviluppatori PHP Catanese e renderla un luogo di confronto dove condividere esperienze lavorative e accresce il proprio bagaglio culturale permettendo a professionisti e appassionati di fare networking.<br />Dopo appena 5 mesi di attività può contare su un centinaio di iscritti e una media di 30 presenze ad evento."

[[params.pug]]
icon = "images/grusp/pugFirenze.svg"
title = "PUG Firenze"
abstract = "Il PUG Firenze vuole essere un luogo di incontro e condivisione per la community di programmatori dell’area di Firenze e dintorni. Non ha ancora potuto fare nessun incontro di persona, a causa delle limitazioni per il coronavirus, ma partecipa attivamente alle attività della community GrUSP ed è felice di fare il suo esordio al phpday PUG Edition!"

[[params.pug]]
icon = "images/grusp/pug-more.png"
title = "PUG MoRe"
abstract = "I primi incontri divulgativi organizzati sono avvenuti tra la fine del 2013 e gli inizi del 2014. Nel 2015 ha organizzato il Symfony Day.<br />Dopo una lunga pausa, con l'intenzione di rinascere dalle ceneri come l'araba fenice, ha ricominciato ad organizzare approfondimenti ed eventi."

[[params.pug]]
icon = "images/grusp/pugPescara.svg"
title = "PUG Pescara"
abstract = "Dopo aver finalmente trovato posto e data per il primo incontro da fare a Marzo, il governo ha provveduto al lockdown di tutta la penisola. <br />La nostra realtà locale vuole diventare un punto di incontro e condivisione per gli sviluppatori di Pescara e dintorni. Nell'attesa di poter riorganizzare un incontro dal vivo, portiamo timidamente la bandiera della nostra regione al phpday PUG edition e partecipiamo alla community del GrUSP."

[[params.pug]]
icon = "images/grusp/pug-roma.png"
title = "PUG Roma"
abstract = "Il PUG Roma nasce nel lontano luglio 2010 come costola locale del GrUSP. Ci incontriamo ogni ultimo martedì del mese e spesso parliamo di tecniche di programmazione, metodologie di sviluppo e di design pattern. Ovviamente parliamo anche di linguaggi e spesso di PHP, ma non ci poniamo limiti in questo senso. Per chi fosse interessato può trovarci su <a href='https://roma.grusp.org' target='_blank'>roma.grusp.org</a>."

[[params.pug]]
icon = "images/grusp/pug-romagna.png"
title = "PUG Romagna"
abstract = "Il PUG Romagna nasce nel dicembre del 2017 dalla volontà di tre sviluppatori che volevano partecipare al PHP Dev Test. <br />Inaugurato ufficialmente con una cena nel gennaio 2018, il PUG Romagna si incontra ogni primo martedì del mese. <br />Come suggerisce il nome, il PUG Romagna si è dato come obiettivo quello di coprire tutto il territorio romagnolo, da Rimini a Faenza, da Ravenna a Cesena: ogni mese il meetup si svolge in una città diversa, per avvicinare tutti gli sviluppatori del territorio e condividere insieme conoscenze, esperienze e nuove opportunità."

[[params.pug]]
icon = "images/grusp/pug-rovigo.png"
title = "PUG Rovigo"
abstract = "Nato nell'estate del 2019 da un gruppo che voleva confrontarsi con le tematiche del framework Scrum e Agile in generale; successivamente ci siamo allargati alla programmazione e gestione delle infrastrutture e dei progetti."

[[params.pug]]
icon = "images/grusp/pugTorino.svg"
abstract = "Il PUG Torino nasce nel 2011 dopo una <a href='http://torino.grusp.org/2011/06/e-nato-il-pug-torino/' target='_blank'>cena in pizzeria tra pochi curiosi</a>. Dopo i primi incontri il gruppo cresce notevolmente di numero al punto da decidere di organizzare delle vere e proprie conferenze nazionali: PHP.TO.START del 2012 e 2013, il primo Symfony Day del 2012 e lo Zend Framework Day del 2014. In questi ultimi anni abbiamo organizzato diversi meetup con frequenza bimestrale affrontando diversi argomenti anche non sempre legati al mondo del PHP. Dal 2018 abbiamo la sponsorship del <a href='https://www.toolboxoffice.it/' target='_blank'>Toolbox coworking di Torino</a> che ci ospita gratuitamente in una sala attrezzata con più di 100 posti a sedere."
title = "PUG Torino"

# programma giorno uno

[[params.giorno_uno]]
orario = "15.00"
title = "Apertura GrUSP"
description = "GrUSP"

[[params.giorno_uno]]
orario = "15.20"
title = "Come funziona un framework: Deep dive nel Request Cycle di Laravel"
description = "“Non so perché... ma funziona!”<br/>Quante volte ve lo siete chiesto? Usare un framework è appagante: in poco tempo siamo operativi, possiamo creare un MVP velocemente e un senso di “magia” ci pervade.<br/>Ma cosa succede dietro le quinte? Questo talk vi aiuterà a capire come funziona il cuore di Laravel e risolvere il vostro dilemma iniziale: “Perché... funziona!”"
author="<a href='https://twitter.com/leorossi' target='_blank'>Leonardo Rossi</a> - PUG Firenze"

[[params.giorno_uno]]
orario = "16.10"
title = "Anteprima delle novità del PHP 8"
description = "In questo talk verranno presentate in anteprima alcune delle novità della prossima major release del PHP. In particolare, analizzeremo le funzionalità del Just In Time compiler (JIT), delle union types, dello static return type, delle weak maps, della nuova interfaccia Stringable e di alcune delle funzionalità deprecate. Proveremo anche a valutare l'impatto sulle performance in confronto con il PHP 7. Su questo tema, approfondiremo il funzionamento del JIT illustrandone i vantaggi e i limiti."
author = "<a href='https://twitter.com/ezimuel' target='_blank'>Enrico Zimuel</a> - PUG Torino"

[[params.giorno_uno]]
orario = "17.00"
title = "Pausa"
description = ""
author = ""

[[params.giorno_uno]]
orario = "17.20"
title = "Server Automation con Laravel Zero"
description = "Esploriamo lo sviluppo di tool in linea di comando con PHP con l'ausilio del Framework Laravel Zero; un tool per chi  vuole cimentarsi con il devops facendo largo uso delle proprie conoscenze da programmatore PHP."
author = "<a href='https://twitter.com/acappellozza' target='_blank'>Alessandro Cappellozza</a> - PUG Rovigo"

[[params.giorno_uno]]
orario = "18.10"
title = "Comunicare, condividere e mantenere decisioni architetturali nei team di sviluppo: approcci e strumenti"
description = "Nella vita quotidiana di un team di sviluppo ci si trova a dover prendere decisioni sull'architettura: implementiamo un sistema basato su CQRS? Quali principi del Domain Driven Design vogliamo applicare e come? Un approccio CRUD è sufficiente in questo contesto?<br />Sia che questa decisione sia presa in modo partecipativo o meno ed indipendentemente dalla risposta, come ci assicuriamo che tutti rispettino la scelta fatta? In questo talk vedremo quali approcci e strumenti abbiamo a disposizione per comunicare, condividere e controllare le decisioni architetturali."
author = "<a href='https://twitter.com/_orso_' target='_blank'>Michele Orselli</a> - PUG Romagna"

[[params.giorno_uno]]
orario = "19.00"
title = "Saluti"
description = "GrUSP"

# programma giorno due

[[params.giorno_due]]
orario = "15.00"
title = "Apertura GrUSP"
description = "GrUSP"

[[params.giorno_due]]
orario = "15.20"
title = "AA.VV. - The old guard of PUG Roma"
description = "In questo panel insieme ad alcuni personaggi illustri appartenenti alla vecchia guardia del PUG Roma parleremo di scelte tecnologiche ed esperienze di vita da developer.<br />Speakers: <a href='https://twitter.com/garakkio' target='_blank'>Massimiliano Arione</a>, <a href='https://twitter.com/cirpo' target='_blank'>Alessandro Cinelli</a>, <a href='https://twitter.com/liuggio' target='_blank'>Giulio De Donato</a>, <a href='https://twitter.com/_odino_' target='_blank'>Alessandro Nadalin</a> e <a href='https://twitter.com/jacoporomei' target='_blank'>Jacopo Romei</a><br />Moderatore: <a href='https://twitter.com/jellybellydev' target='_blank'>Andrea Giannantonio</a>"
author = "PUG Roma"

[[params.giorno_due]]
orario = "16.10"
title = "TDD💙BDD💙PHP - Sviluppo guidato dai test in PHP con phpspec"
description = "Phpspec è uno strumento che può aiutarci a scrivere codice pulito e funzionante facilitandoci nell'adottare delle pratiche di Behaviour-Driven Development (BDD). Ma cos’è il BDD? Qual è la differenza tra il BDD e il Test-Driven Development (TDD)? Quali sono le differenze tra le famiglie di tool xSpec e xUnit? Quali strumenti mette a disposizione l’ecosistema PHP per praticare il TDD? Infine passeremo dalla teoria alla pratica risolvendo un problema in TDD con phpspec."
author = "<a href='https://www.linkedin.com/in/patrickfazzi' target='_blank'>Patrick Luca Fazzi</a> - PUG Catania"

[[params.giorno_due]]
orario = "17.00"
title = "Pausa"
description = ""

[[params.giorno_due]]
orario = "17.20"
title = "Filtering API: API REST con alcune comodità di GraphQL"
description = "Le API REST sono il motore dei nostri frontend. Vediamo come evitare di riscrivere troppo codice dando liberà al client di interrogare le API con delle opzioni per ordinare e filtrare in maniera autonoma.<br />Verranno presentati due approcci, uno basato sul query builder di Spatie per Laravel e uno basato su una semplice classe personalizzabile all'occorrenza"
author = "<a href='https://twitter.com/_Oniz_' target='_blank'>Teo Miscia</a> - PUG Pescara"

[[params.giorno_due]]
orario = "18.10"
title = "composer require Wordpress"
description = "Diciamoci la verità non proprio a tutti piace Wordpress, ma se Wordpress fosse una semplice dipendenza del nostro progetto?<br />Durante l'incontro vi mostrerò uno use-case e i vantaggi che ha portato questo tipo di approccio nello sviluppo di un sito Wordpress."
author = "<a href='https://twitter.com/Albero92' target='_blank'>Giovanni Albero</a> - PUG MoRe"

[[params.giorno_due]]
orario = "19.00"
title = "Saluti"
description = "GrUSP"

# social icon
[[params.socialIcon]]
icon = "ion-social-facebook"
url = "https://www.facebook.com/GrUSP/"

[[params.socialIcon]]
icon = "ion-social-twitter"
url = "https://twitter.com/grusp"

[[params.socialIcon]]
icon = "ion-social-linkedin"
url = "https://www.linkedin.com/company/grusp/"
